### ISSUE TITLE
Connexion à la base de données

### ISSUE THREAD

**Issue by Destroy-9** [Destroy-9/Lugdunum_Back_End#2]
Installer les modules nécessaires au fonctionnement de GraphQl et établir la connexion à la base de données choisie (MongoDB)
- npm install -g graphql
- npm install -g express-graphql

**Comment by RemiChbrnt** [comment]
Quelques liens pour commencer GraphQL :
https://graphql.org/graphql-js/running-an-express-graphql-server/
https://www.compose.com/articles/using-graphql-with-mongodb/
https://codingthesmartway.com/creating-a-graphql-server-with-node-js-and-express/

**Comment by RemiChbrnt** [comment]
Connexion à MongoDB effectuée, aucune utilisation de celle-ci pour le moment.
