### ISSUE TITLE
Récupération des données de géolocalisation

### ISSUE THREAD

**Issue by Destroy-9** [Destroy-9/Lugdunum_Back_End#4]
Requête Http POST qui récupère les données GPS depuis le frontend applicatif et l'enregistre dans la base de données :
- Longitude en float
- Latitude en float
- Heure de la mesure en date

**Comment by RemiChbrnt** [comment]
Premiers objets à créer avec GraphQL du type :
User: {id, password, localization{time, lat, long}}
